export const GET_NOVELS = 'GET_NOVELS';
export const GET_NOVELS_SUCCESS = 'GET_NOVELS_SUCCESS';
export const GET_NOVELS_ERROR = 'GET_NOVELS_ERROR';

export const POST_NOVELS = 'POST_NOVELS';
export const POST_NOVELS_SUCCESS = 'POST_NOVELS_SUCCESS';
export const POST_NOVELS_ERROR = 'POST_NOVELS_ERROR';

export const UPDATE_NOVELS = 'UPDATE_NOVELS';
export const UPDATE_NOVELS_SUCCESS = 'UPDATE_NOVELS_SUCCESS';
export const UPDATE_NOVELS_ERROR = 'UPDATE_NOVELS_ERROR';

export const DELETE_NOVELS = 'DELETE_NOVELS';
export const DELETE_NOVELS_SUCCESS = 'DELETE_NOVELS_SUCCESS';
export const DELETE_NOVELS_ERROR = 'DELETE_NOVELS_ERROR';